In [1]:
import pandas as pd
import numpy as np

In [2]:
df_cost = pd.read_csv('cost_per_material.csv')
df_cost.head()

       Item Code  Cost per material     Month
0  32A4A7-SEKA1P                8.0  1/1/2025
1  32A4B2-SEBA1P                8.0  1/1/2025
2  32A4B2-SEEA1P                7.0  1/1/2025
3  32A4B2-SEOA1P                8.0  1/1/2025
4  32A4B3-SEBA1P                7.0  1/1/2025

In [3]:
df_supply = pd.read_csv('global_supply.csv')
df_supply.head()

      Month  global_prod
0  1/1/2004       282574
1  1/2/2004       187742
2  1/3/2004       239666
3  1/4/2004       212569
4  1/5/2004       261301